#!/bin/bash

file="$1"
if ! [ "$file" = "" ]
then
    exec_name=$(basename "$file" ".c")
    gcc -g -Wall "$file" -o "$exec_name"
    ./"$exec_name"
    rm "$exec_name"
else
    echo "error: no file name passed"
fi
