#!/bin/bash

file="$1"
if ! [ "$file" = "" ]
then
    exec_name=$(basename "$file" ".c")
    if ! ( gcc -g -Wall $@ -o "$exec_name" )
    then
        ./"$exec_name"
        rm "$exec_name"
    fi
else
    echo "error: no file name passed"
fi
